### ISSUE TITLE
分类页面暂无数据

### ISSUE THREAD

**Issue by dawnabout** [wangwenzhiwwz/WX#7]
您好，想问下是不是分类页面的代码不完整呀。小程序调试发现分类里面的内容点进去显示暂无数据
![image](https://github.com/wangwenzhiwwz/WX/assets/75124227/54ad6ecc-18b0-4aeb-b266-10c954994ef5)

**Comment by woniudiancang** [comment]
扫码体验，城市主题正常显示，未复现你所说的问题

**Comment by gooking** [comment]
扫码体验，城市主题是有数据的，未发现你所说的问题
